# Generated by Django 4.1.1 on 2022-09-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('producer', models.CharField(blank=True, max_length=30)),
                ('rate', models.FloatField(default=0)),
                ('time', models.FloatField(default=0)),
            ],
        ),
    ]
