# Generated by Django 4.1.1 on 2022-09-22 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'фильмы'},
        ),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.CharField(blank=True, max_length=30, verbose_name='продюссер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rate',
            field=models.FloatField(default=0, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='film',
            name='time',
            field=models.FloatField(default=0, verbose_name='длительность'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=80, verbose_name='заголовок'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Что думаете о фильме?')),
                ('rate_user', models.FloatField(blank=True, verbose_name='оценка')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.film')),
            ],
            options={
                'verbose_name': 'коммент',
                'verbose_name_plural': 'комметарии',
            },
        ),
    ]
