# Generated by Django 4.1.1 on 2022-10-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_comments_created_at_alter_film_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at'], 'verbose_name': 'коммент', 'verbose_name_plural': 'комметарии'},
        ),
    ]
